### ISSUE TITLE
error Command "build" not found.

### ISSUE THREAD

**Issue by hadv** [amanusk/hardhat-template#5]
Hi @amanusk 

 I run `yarn build` but error happen. It seems that we forgot to put **_build_** into the `package.json` file? atm, there're two scripts only

```
  "scripts": {
    "compile": "npx hardhat compile",
    "test": "npx hardhat test"
  },
```

**ERROR:**
```
% yarn build
yarn run v1.22.5
error Command "build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amanusk** [comment]
Yea, thanks, I updated the README, there should be only yarn compile.
No hardhat-typechain only creates new types if anything changed.

**Comment by hadv** [comment]
> Yea, thanks, I updated the README, there should be only yarn compile.
> No hardhat-typechain only creates new types if anything changed.

Thanks, can you guide me how to build typechain when I adding new smart contract into project for testing, please?

**Comment by hadv** [comment]
> > Yea, thanks, I updated the README, there should be only yarn compile.
> > No hardhat-typechain only creates new types if anything changed.
> 
> Thanks, can you guide me how to build typechain when I adding new smart contract into project for testing, please?

we might add it into hardhat config, no?

```
  typechain: {
    outDir: "typechain",
    target: "ethers-v5",
  },
```

**Comment by hadv** [comment]
> we might add it into hardhat config, no?

I make a PR #6  for it. PTAL!

**Comment by amanusk** [comment]
Thanks. For me the typechain dir was auto-created, but it cant hurt. Does it solve your issue?

**Comment by hadv** [comment]
> Thanks. For me the typechain dir was auto-created, but it cant hurt. Does it solve your issue?

Yes, it can generate new typechain when running `yarn compile` if there's any new smart contract
